/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

		/*****************System Clock =32 MHZ*******************/
#define RCC_BASE        			0x40021000
#define RCC_CR            *((unsigned volatile int*)(RCC_BASE+0x0))
#define RCC_CFGR          *((unsigned volatile int*)(RCC_BASE+0x04))
#define RCC_APB2ENR       *((unsigned volatile int*)(RCC_BASE+0x18))

		/*****************GPIOA********************/
#define GPIOA_BASE        			0x40010800
#define GPIOA_CRL         *((unsigned volatile int*)(GPIOA_BASE+0x0))
#define GPIOA_ODR         *((unsigned volatile int*)(GPIOA_BASE+0x0C))

				/*****************EXTI0***************/
#define EXTI_BASE                   0x40010400
#define EXTI_IMR          *((unsigned volatile int*)(EXTI_BASE+0x0))
#define EXTI_RTSR         *((unsigned volatile int*)(EXTI_BASE+0x08))
#define EXTI_PR			  *((unsigned volatile int*)(EXTI_BASE+0x14))

			/************************NVIC**********************/
#define NVIC_BASE                   0xE000E000
#define NVIC_EN         *((unsigned volatile int*)(NVIC_BASE+0x100))

void Clock_Init_32MHz(void)
{
	RCC_CFGR &=~(1<<16);
	RCC_CFGR|=((0b0110)<<18);
	RCC_CFGR|=2;
	RCC_CR|=(1<<24);
}

void GPIOA_INIT(void)
{
	RCC_APB2ENR|=(1<<2);
	GPIOA_CRL|=(1<<5);
	GPIOA_CRL&=~ (1<<6);
	EXTI_IMR|=0x1;
	EXTI_RTSR|=0x1;
	NVIC_EN|=(1<<6);
}

int main(void)
{
	Clock_Init_32MHz();
	GPIOA_INIT();
    /* Loop forever */
	while (1)
	{
		/*DO Nothing*/
	}
}
void EXTI0_IRQHandler(void)
{
	GPIOA_ODR^=(1<<1);
	EXTI_PR|=(1<<0);
}
