/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

		/*****************System Clock =32 MHZ*******************/
#define RCC_BASE        			0x40021000
#define RCC_CR            *((unsigned volatile int*)(RCC_BASE+0x0))
#define RCC_CFGR          *((unsigned volatile int*)(RCC_BASE+0x04))
#define RCC_APB2ENR       *((unsigned volatile int*)(RCC_BASE+0x18))

		/*****************GPIOA********************/
#define GPIOA_BASE        			0x40010800
#define GPIOA_CRL         *((unsigned volatile int*)(GPIOA_BASE+0x00))
#define GPIOA_CRH         *((unsigned volatile int*)(GPIOA_BASE+0x04))
#define GPIOA_ODR         *((unsigned volatile int*)(GPIOA_BASE+0x0C))
#define GPIOA_IDR         *((unsigned volatile int*)(GPIOA_BASE+0x08))

       /*****************GPIOB********************/
#define GPIOB_BASE        			0x40010C00
#define GPIOB_CRL         *((unsigned volatile int*)(GPIOB_BASE+0x00))
#define GPIOB_CRH         *((unsigned volatile int*)(GPIOB_BASE+0x04))
#define GPIOB_ODR         *((unsigned volatile int*)(GPIOB_BASE+0x0C))

void Clock_Init_32MHz(void)
{
	RCC_CFGR &=~(1<<16);
	RCC_CFGR|=((0b0110)<<18);
	RCC_CFGR|=2;
	RCC_CR|=(1<<24);
}

void GPIO_INIT(void)
{
	RCC_APB2ENR|=(1<<2);
	RCC_APB2ENR|=(1<<3);

	GPIOA_CRL &=~ (1<<4);
	GPIOA_CRL |=(1<<6);

	GPIOB_CRH |=(1<<20);
	GPIOB_CRH &= ~ (1<<22);
}

int main(void)
{
	Clock_Init_32MHz();
	GPIO_INIT();

    /* Loop forever */
	while (1)
	{
		if (((GPIOA_IDR>>1)&1)==0)
		{
			GPIOB_ODR ^= (1<<13);
			while (((GPIOA_IDR>>1)&1) == 0);
		}
	}
}
